name: Publish to npm

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - name: Build UMD
        run: npm run build-umd
      - name: Check Version
        if: github.ref == 'refs/heads/main' 
        id: check_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"alpha"* || $VERSION == *"beta"* ]]; then
            echo "::error::Version contains alpha or beta tag. Cannot publish to main."
            exit 1
          fi
      - name: Publish
        if: steps.check_version.outcome == 'success' || github.ref == 'refs/heads/develop' 
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            npm publish --access public
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            npm publish --tag beta --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload CSS Prd
        run: | 
          VERSION=$(node -p "require('./package.json').version")
          aws s3 cp dist/luminusdaisy.umd.css s3://${{ env.S3_BUCKET_NAME }}/library/luminus-daisy/${{ $VERSION }}/assets/luminusdaisy.umd.css
      - name: Upload CSS Dev
        run: |
          VERSION=$(node -p "require('./package.json').version")
          aws s3 cp dist/luminusdaisy.umd.dev.css s3://${{ env.S3_BUCKET_NAME }}/library/luminus-daisy/${{ $VERSION }}/assets/luminusdaisy.umd.dev.css
      - name: Upload JS Prd
        run: |
          VERSION=$(node -p "require('./package.json').version")
          aws s3 cp dist/luminusdaisy.umd.js s3://${{ env.S3_BUCKET_NAME }}/library/luminus-daisy/${{ $VERSION }}/assets/luminusdaisy.umd.js
      - name: Upload JS Dev
        run: |
          VERSION=$(node -p "require('./package.json').version")
          aws s3 cp dist/luminusdaisy.umd.dev.js s3://${{ env.S3_BUCKET_NAME }}/library/luminus-daisy/${{ $VERSION }}/assets/luminusdaisy.umd.dev.js
